server:
  port: 8081  #这里的端口号会被激活的文档快prod中的port覆盖
  #context-path: /springbootdemo
logging:
  config: classpath:log4j2.xml
spring:
  profiles:
    active: prod #激活prod文档快，prod文档块和当前文档快互补，但功能相同时prod文档块会覆盖当前文档快
#spingboot启动时候会把此配置文件prifix=flower的值绑定到Flower对象中
flower:
  name: rose
  color: red
#spingboot启动时候会把此配置文件prifix=person的值绑定到Person对象中
person:
  height: 170
  weight: ${person.height}
  list:
  - zhangsan
  - lisi
  map: {k1: 11,k2: 22}
  dog:
    name: dahuang
    age: ${random.int}
rectangle: #这里绑定到对象的属性会被激活的文档快prod中的Rectangle覆盖
  length: 3


---
# (三个-)表示一个文档块
server:
  port: 8082
spring:
  profiles: dev #文档块的名字叫dev

---
# (三个-)表示一个文档块
server:
  port: 8083
spring:
  profiles: prod #文档块的名字叫prod
rectangle:
  length: 6